name: deepchem-api
channels:
  - dglteam/label/th22_cu118
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - dgl
  - numpy=1.26.4
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - pytorch-cuda=11.8
  - dgllife
  - pip
  - pip:
    - -r requirements.txt 